version: 2

models:
    - name: campaigns_v2_dbt
      description: "campaigns v2"
      config:
          enabled: true
          tags: campaigns_v2
    - name: campaign_expenses_transformed_dbt
      description: "campaign expenses transformed"
      config:
          enabled: true
          tags: campaign_expenses_transformed
    - name: marketing_leads_v2_dbt
      description: "marketing leads v2 table"
      config:
          enabled: true
          tags: marketing_leads_v2
    - name: independent_expenses_dbt
      description: "independent expenses table"
      config:
          enabled: true
          tags: independent_expenses
    - name: unhidden_noleads_dbt
      description: "unidden with no leads table"
      config:
          enabled: true
          tags: unhidden_noleads
    - name: marketing_leads_transformed_v2_dbt
      description: "marketing leads transformed table"
      config:
          enabled: true
          tags: marketing_leads_transformed
    - name: marketing_leads_cost_dbt
      description: "marketing leads cost table"
      config:
          enabled: true
          tags: marketing_leads_cost