version: 2

models:
    - name: campaigns_v2_dbt
      description: "campaigns v2"
      config:
          enabled: true
          tags: campaigns_v2
    - name: campaign_expenses_transformed_dbt
      description: "campaign expenses transformed"
      config:
          enabled: true
          tags: campaign_expenses_transformed
    - name: inhouse_data
      description: "distinct inhouse data values"
      config:
          enabled: true
          tags: inhouse_data
    - name: marketing_leads_v2_dbt
      description: "marketing leads v2 table"
      config:
          enabled: true
          tags: marketing_leads_v2
    - name: ml_invalid_statuses
      description: "distinct invalid statuses"
      config:
          enabled: true
          tags: ml_invalid_statuses
    - name: independent_expenses_dbt
      description: "independent expenses table"
      config:
          enabled: true
          tags: independent_expenses
    - name: unhidden_noleads_dbt
      description: "unidden with no leads table"
      config:
          enabled: true
          tags: unhidden_noleads
    - name: marketing_leads_transformed_v2_dbt
      description: "marketing leads transformed table"
      config:
          enabled: true
          tags: marketing_leads_transformed
    - name: marketing_leads_cost_dbt
      description: "marketing leads cost table"
      config:
          enabled: true
          tags: marketing_leads_cost
    - name: sales_transactions_rejected
      description: "rejected transaction reasons"
      config:
          enabled: true
          tags: sales_transactions_rejected
    - name: sales_transactions_all
      description: "all transactions including non unique"
      config:
          enabled: true
          tags: sales_transactions_all
    - name: dialer_languages
      description: "dialer language mapping"
      config:
          enabled: true
          tags: dialer_languages
    - name: live_late_ftds
      description: "live and late ftds report"
      config:
          enabled: true
          tags: live_late_ftds
    - name: engagement_stats
      description: "by engagement status report"
      config:
          enabled: true
          tags: engagement_stats
    - name: fx_rates
      description: "forex rates"
      config:
          enabled: true
          tags: fx_rates